#!/bin/bash

set -e

K8S_VERSION="1.13.6-00"

locale-gen en_US.UTF-8
c_rehash /etc/ssl/certs

apt update
apt upgrade -y
apt install -y \
  apt-transport-https \
  curl \
  gnupg

curl https://archive.raspberrypi.org/debian/raspberrypi.gpg.key | apt-key add -
echo "deb https://archive.raspberrypi.org/debian stretch main" > /etc/apt/sources.list.d/raspberrypi.list
curl https://download.docker.com/linux/raspbian/gpg | apt-key add -
echo "deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable" > /etc/apt/sources.list.d/docker.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb http://apt.kubernetes.io kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

apt update
apt install -y --no-install-recommends \
  raspberrypi-bootloader \
  raspberrypi-kernel \
  docker-ce
apt install -y \
  bash-completion \
  dnsutils \
  ethtool \
  fake-hwclock \
  haveged \
  htop \
  iftop \
  ifupdown \
  iotop \
  kubeadm=$K8S_VERSION \
  kubectl=$K8S_VERSION \
  kubelet=$K8S_VERSION \
  net-tools \
  openssh-server \
  screen \
  ubuntu-release-upgrader-core \
  unattended-upgrades \
  vim \
  vlan
sudo apt-mark hold \
  kubeadm \
  kubectl \
  kubelet

systemctl disable syslog
systemctl disable motd-news.service
systemctl disable motd-news.timer
systemctl enable docker
systemctl enable haveged

sed -i "s/%sudo	ALL=(ALL:ALL) ALL/%sudo	ALL=(ALL:ALL) NOPASSWD:ALL/g" /etc/sudoers
sed -i "s/    HashKnownHosts yes/#   HashKnownHosts yes/g" /etc/ssh/ssh_config

rm /etc/update-motd.d/10-help-text
rm /etc/update-motd.d/50-motd-news
rm /etc/ssh/ssh_host_*

dpkg-reconfigure tzdata

apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
